spring:
  application:
    name: identity-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/identity_service?sslmode=require&prepareThreshold=0
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      data-source-properties:
        prepareThreshold: 0

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 8090
  servlet:
    context-path: /identity

springdoc:
  paths-to-match: /**
  packages-to-scan: com.dts.entry.identityservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
