spring:
  application:
    name: identity-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8090
  servlet:
    context-path: /identity

springdoc:
  paths-to-match: /**
  packages-to-scan: com.dts.entry.identityservice.controller
  swagger-ui:
    path: /swagger-ui
    oauth:
      use-pkce-with-authorization-code-grant: true
      client-id: swagger-ui
