spring:
  application:
    name: api-gateway

server:
  port: 9191

management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    urls:
      - name: identity-service
        url: http://${domain.identity-service}/api/v1/identity/v3/api-docs
      - name: profile-service
        url: http://${domain.profile-service}/api/v1/user/v3/api-docs

client:
  domain: ${CLIENT_DOMAIN}

domain:
  identity-service: ${IDENTITY_SERVICE_DOMAIN}
  profile-service: ${PROFILE_SERVICE_DOMAIN}
  gateway: ${GATEWAY_DOMAIN}